edition = "2021"
version = "Two"
unstable_options = true 

max_width = 120
comment_width = 120
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Vertical"
wrap_comments = true

